directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/core/INIT_LOOP_HLS:acc#8.itm REGISTER_NAME INIT_LOOP_HLS:acc#8.itm
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/core/hist8:vinit.ndx(7:0).sva REGISTER_NAME INIT_LOOP_HLS:acc#8.itm
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/core/INIT_LOOP_HLS:acc#7.itm REGISTER_NAME INIT_LOOP_HLS:acc#7.itm
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/core/hist7:vinit.ndx(7:0).sva REGISTER_NAME INIT_LOOP_HLS:acc#7.itm
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/core/INIT_LOOP_HLS:acc#6.itm REGISTER_NAME INIT_LOOP_HLS:acc#6.itm
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/core/hist6:vinit.ndx(7:0).sva REGISTER_NAME INIT_LOOP_HLS:acc#6.itm
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/core/INIT_LOOP_HLS:acc#5.itm REGISTER_NAME INIT_LOOP_HLS:acc#5.itm
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/core/hist5:vinit.ndx(7:0).sva REGISTER_NAME INIT_LOOP_HLS:acc#5.itm
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/core/INIT_LOOP_HLS:acc#4.itm REGISTER_NAME INIT_LOOP_HLS:acc#4.itm
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/core/hist4:vinit.ndx(7:0).sva REGISTER_NAME INIT_LOOP_HLS:acc#4.itm
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/core/INIT_LOOP_HLS:acc#3.itm REGISTER_NAME INIT_LOOP_HLS:acc#3.itm
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/core/hist3:vinit.ndx(7:0).sva REGISTER_NAME INIT_LOOP_HLS:acc#3.itm
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/core/INIT_LOOP_HLS:acc.itm REGISTER_NAME INIT_LOOP_HLS:acc.itm
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/core/hist1:vinit.ndx(7:0).sva REGISTER_NAME INIT_LOOP_HLS:acc.itm
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/core/count(13:3).sva(9:0) REGISTER_NAME count(13:3).sva(9:0)
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/core/INIT_LOOP_HLS:acc#2.itm REGISTER_NAME count(13:3).sva(9:0)
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/core/hist2:vinit.ndx(7:0).sva REGISTER_NAME count(13:3).sva(9:0)
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/core/accum_loop:i(8:0).sva(7:0) REGISTER_NAME count(13:3).sva(9:0)
