directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/histogram_hls:core:conc/accum_loop:acc#13 RESOURCE_NAME INIT_LOOP_HLS:acc#7:rg
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/histogram_hls:core:conc/INIT_LOOP_HLS:acc#7 RESOURCE_NAME INIT_LOOP_HLS:acc#7:rg
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/histogram_hls:core:conc/accum_loop:acc#12 RESOURCE_NAME INIT_LOOP_HLS:acc:rg
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/histogram_hls:core:conc/INIT_LOOP_HLS:acc RESOURCE_NAME INIT_LOOP_HLS:acc:rg
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/histogram_hls:core:conc/accum_loop:acc#11 RESOURCE_NAME INIT_LOOP_HLS:acc#3:rg
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/histogram_hls:core:conc/INIT_LOOP_HLS:acc#3 RESOURCE_NAME INIT_LOOP_HLS:acc#3:rg
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/histogram_hls:core:conc/accum_loop:acc#10 RESOURCE_NAME INIT_LOOP_HLS:acc#5:rg
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/histogram_hls:core:conc/INIT_LOOP_HLS:acc#5 RESOURCE_NAME INIT_LOOP_HLS:acc#5:rg
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/histogram_hls:core:conc/INIT_LOOP_HLS:acc#2 RESOURCE_NAME INIT_LOOP_HLS:acc#2:rg
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/histogram_hls:core:conc/hist_loop:acc#8 RESOURCE_NAME INIT_LOOP_HLS:acc#2:rg
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/histogram_hls:core:conc/accum_loop:acc#9 RESOURCE_NAME INIT_LOOP_HLS:acc#2:rg
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/histogram_hls:core:conc/hist_loop:hist_loop:acc#1 RESOURCE_NAME INIT_LOOP_HLS:acc#2:rg
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/histogram_hls:core:conc/hist_loop:hist_loop:acc#3 RESOURCE_NAME INIT_LOOP_HLS:acc#2:rg
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/histogram_hls:core:conc/hist_loop:hist_loop:acc#5 RESOURCE_NAME INIT_LOOP_HLS:acc#2:rg
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/histogram_hls:core:conc/hist_loop:hist_loop:acc#7 RESOURCE_NAME INIT_LOOP_HLS:acc#2:rg
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/histogram_hls:core:conc/hist_loop:hist_loop:acc#9 RESOURCE_NAME INIT_LOOP_HLS:acc#2:rg
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/histogram_hls:core:conc/hist_loop:hist_loop:acc#11 RESOURCE_NAME INIT_LOOP_HLS:acc#2:rg
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/histogram_hls:core:conc/hist_loop:hist_loop:acc#13 RESOURCE_NAME INIT_LOOP_HLS:acc#2:rg
directive set /histogram_hls/histogram_hls.struct/histogram_hls:core/histogram_hls:core:conc/hist_loop:hist_loop:acc#15 RESOURCE_NAME INIT_LOOP_HLS:acc#2:rg
