// Generated by ZYANG
#ifndef INCLUDED_CCS_DUT_WRAPPER_H
#define INCLUDED_CCS_DUT_WRAPPER_H

#ifndef SC_USE_STD_STRING
#define SC_USE_STD_STRING
#endif

#include <systemc.h>
#include <mc_simulator_extensions.h>

#ifdef CCS_SYSC
namespace HDL {
#endif
#if defined(CCS_DUT_SYSC)
// alias ccs_DUT_wrapper to namespace enclosure of either cycle or RTL SystemC netlist
namespace
    ccs_design {
#if defined(CCS_DUT_CYCLE)
#include "cycle.cxx"
#else
#if defined(CCS_DUT_RTL)
#include "rtl.cxx"
#endif
#endif
}
typedef
    ccs_design::HDL::histogram_hls ccs_DUT_wrapper;

#else

// Create a foreign module wrapper around the HDL
#ifdef VCS_SYSTEMC
// VCS support - ccs_DUT_wrapper is derived from VCS-generated SystemC wrapper around HDL code
class ccs_DUT_wrapper : public TOP_HDL_ENTITY
{
public:
  ccs_DUT_wrapper(const sc_module_name& nm, const char *hdl_name)
  : TOP_HDL_ENTITY(nm)
  {
  // elaborate_foreign_module(hdl_name);
  }

  ~ccs_DUT_wrapper() {}
};

#else
// non VCS simulators - ccs_DUT_wrapper is derived from mc_foreign_module (adding 2nd ctor arg)
class ccs_DUT_wrapper: public mc_foreign_module
{
public:
  // Interface Ports
  sc_in<bool> clk;
  sc_in<sc_logic> rst;
  sc_in<sc_logic> data_in_rsc_s_tdone;
  sc_in<sc_logic> data_in_rsc_tr_write_done;
  sc_in<sc_logic> data_in_rsc_RREADY;
  sc_out<sc_logic> data_in_rsc_RVALID;
  sc_out<sc_logic> data_in_rsc_RUSER;
  sc_out<sc_logic> data_in_rsc_RLAST;
  sc_out<sc_lv<2> > data_in_rsc_RRESP;
  sc_out<sc_lv<16> > data_in_rsc_RDATA;
  sc_out<sc_logic> data_in_rsc_RID;
  sc_out<sc_logic> data_in_rsc_ARREADY;
  sc_in<sc_logic> data_in_rsc_ARVALID;
  sc_in<sc_logic> data_in_rsc_ARUSER;
  sc_in<sc_lv<4> > data_in_rsc_ARREGION;
  sc_in<sc_lv<4> > data_in_rsc_ARQOS;
  sc_in<sc_lv<3> > data_in_rsc_ARPROT;
  sc_in<sc_lv<4> > data_in_rsc_ARCACHE;
  sc_in<sc_logic> data_in_rsc_ARLOCK;
  sc_in<sc_lv<2> > data_in_rsc_ARBURST;
  sc_in<sc_lv<3> > data_in_rsc_ARSIZE;
  sc_in<sc_lv<8> > data_in_rsc_ARLEN;
  sc_in<sc_lv<13> > data_in_rsc_ARADDR;
  sc_in<sc_logic> data_in_rsc_ARID;
  sc_in<sc_logic> data_in_rsc_BREADY;
  sc_out<sc_logic> data_in_rsc_BVALID;
  sc_out<sc_logic> data_in_rsc_BUSER;
  sc_out<sc_lv<2> > data_in_rsc_BRESP;
  sc_out<sc_logic> data_in_rsc_BID;
  sc_out<sc_logic> data_in_rsc_WREADY;
  sc_in<sc_logic> data_in_rsc_WVALID;
  sc_in<sc_logic> data_in_rsc_WUSER;
  sc_in<sc_logic> data_in_rsc_WLAST;
  sc_in<sc_lv<2> > data_in_rsc_WSTRB;
  sc_in<sc_lv<16> > data_in_rsc_WDATA;
  sc_out<sc_logic> data_in_rsc_AWREADY;
  sc_in<sc_logic> data_in_rsc_AWVALID;
  sc_in<sc_logic> data_in_rsc_AWUSER;
  sc_in<sc_lv<4> > data_in_rsc_AWREGION;
  sc_in<sc_lv<4> > data_in_rsc_AWQOS;
  sc_in<sc_lv<3> > data_in_rsc_AWPROT;
  sc_in<sc_lv<4> > data_in_rsc_AWCACHE;
  sc_in<sc_logic> data_in_rsc_AWLOCK;
  sc_in<sc_lv<2> > data_in_rsc_AWBURST;
  sc_in<sc_lv<3> > data_in_rsc_AWSIZE;
  sc_in<sc_lv<8> > data_in_rsc_AWLEN;
  sc_in<sc_lv<13> > data_in_rsc_AWADDR;
  sc_in<sc_logic> data_in_rsc_AWID;
  sc_in<sc_logic> data_in_rsc_req_vz;
  sc_out<sc_logic> data_in_rsc_rls_lz;
  sc_in<sc_logic> hist_out_rsc_s_tdone;
  sc_in<sc_logic> hist_out_rsc_tr_write_done;
  sc_in<sc_logic> hist_out_rsc_RREADY;
  sc_out<sc_logic> hist_out_rsc_RVALID;
  sc_out<sc_logic> hist_out_rsc_RUSER;
  sc_out<sc_logic> hist_out_rsc_RLAST;
  sc_out<sc_lv<2> > hist_out_rsc_RRESP;
  sc_out<sc_lv<8> > hist_out_rsc_RDATA;
  sc_out<sc_logic> hist_out_rsc_RID;
  sc_out<sc_logic> hist_out_rsc_ARREADY;
  sc_in<sc_logic> hist_out_rsc_ARVALID;
  sc_in<sc_logic> hist_out_rsc_ARUSER;
  sc_in<sc_lv<4> > hist_out_rsc_ARREGION;
  sc_in<sc_lv<4> > hist_out_rsc_ARQOS;
  sc_in<sc_lv<3> > hist_out_rsc_ARPROT;
  sc_in<sc_lv<4> > hist_out_rsc_ARCACHE;
  sc_in<sc_logic> hist_out_rsc_ARLOCK;
  sc_in<sc_lv<2> > hist_out_rsc_ARBURST;
  sc_in<sc_lv<3> > hist_out_rsc_ARSIZE;
  sc_in<sc_lv<8> > hist_out_rsc_ARLEN;
  sc_in<sc_lv<12> > hist_out_rsc_ARADDR;
  sc_in<sc_logic> hist_out_rsc_ARID;
  sc_in<sc_logic> hist_out_rsc_BREADY;
  sc_out<sc_logic> hist_out_rsc_BVALID;
  sc_out<sc_logic> hist_out_rsc_BUSER;
  sc_out<sc_lv<2> > hist_out_rsc_BRESP;
  sc_out<sc_logic> hist_out_rsc_BID;
  sc_out<sc_logic> hist_out_rsc_WREADY;
  sc_in<sc_logic> hist_out_rsc_WVALID;
  sc_in<sc_logic> hist_out_rsc_WUSER;
  sc_in<sc_logic> hist_out_rsc_WLAST;
  sc_in<sc_logic> hist_out_rsc_WSTRB;
  sc_in<sc_lv<8> > hist_out_rsc_WDATA;
  sc_out<sc_logic> hist_out_rsc_AWREADY;
  sc_in<sc_logic> hist_out_rsc_AWVALID;
  sc_in<sc_logic> hist_out_rsc_AWUSER;
  sc_in<sc_lv<4> > hist_out_rsc_AWREGION;
  sc_in<sc_lv<4> > hist_out_rsc_AWQOS;
  sc_in<sc_lv<3> > hist_out_rsc_AWPROT;
  sc_in<sc_lv<4> > hist_out_rsc_AWCACHE;
  sc_in<sc_logic> hist_out_rsc_AWLOCK;
  sc_in<sc_lv<2> > hist_out_rsc_AWBURST;
  sc_in<sc_lv<3> > hist_out_rsc_AWSIZE;
  sc_in<sc_lv<8> > hist_out_rsc_AWLEN;
  sc_in<sc_lv<12> > hist_out_rsc_AWADDR;
  sc_in<sc_logic> hist_out_rsc_AWID;
  sc_in<sc_logic> hist_out_rsc_req_vz;
  sc_out<sc_logic> hist_out_rsc_rls_lz;
public:
  ccs_DUT_wrapper(const sc_module_name& nm, const char *hdl_name)
  :
    mc_foreign_module(nm, hdl_name), 
    clk("clk"), 
    rst("rst"), 
    data_in_rsc_s_tdone("data_in_rsc_s_tdone"), 
    data_in_rsc_tr_write_done("data_in_rsc_tr_write_done"), 
    data_in_rsc_RREADY("data_in_rsc_RREADY"), 
    data_in_rsc_RVALID("data_in_rsc_RVALID"), 
    data_in_rsc_RUSER("data_in_rsc_RUSER"), 
    data_in_rsc_RLAST("data_in_rsc_RLAST"), 
    data_in_rsc_RRESP("data_in_rsc_RRESP"), 
    data_in_rsc_RDATA("data_in_rsc_RDATA"), 
    data_in_rsc_RID("data_in_rsc_RID"), 
    data_in_rsc_ARREADY("data_in_rsc_ARREADY"), 
    data_in_rsc_ARVALID("data_in_rsc_ARVALID"), 
    data_in_rsc_ARUSER("data_in_rsc_ARUSER"), 
    data_in_rsc_ARREGION("data_in_rsc_ARREGION"), 
    data_in_rsc_ARQOS("data_in_rsc_ARQOS"), 
    data_in_rsc_ARPROT("data_in_rsc_ARPROT"), 
    data_in_rsc_ARCACHE("data_in_rsc_ARCACHE"), 
    data_in_rsc_ARLOCK("data_in_rsc_ARLOCK"), 
    data_in_rsc_ARBURST("data_in_rsc_ARBURST"), 
    data_in_rsc_ARSIZE("data_in_rsc_ARSIZE"), 
    data_in_rsc_ARLEN("data_in_rsc_ARLEN"), 
    data_in_rsc_ARADDR("data_in_rsc_ARADDR"), 
    data_in_rsc_ARID("data_in_rsc_ARID"), 
    data_in_rsc_BREADY("data_in_rsc_BREADY"), 
    data_in_rsc_BVALID("data_in_rsc_BVALID"), 
    data_in_rsc_BUSER("data_in_rsc_BUSER"), 
    data_in_rsc_BRESP("data_in_rsc_BRESP"), 
    data_in_rsc_BID("data_in_rsc_BID"), 
    data_in_rsc_WREADY("data_in_rsc_WREADY"), 
    data_in_rsc_WVALID("data_in_rsc_WVALID"), 
    data_in_rsc_WUSER("data_in_rsc_WUSER"), 
    data_in_rsc_WLAST("data_in_rsc_WLAST"), 
    data_in_rsc_WSTRB("data_in_rsc_WSTRB"), 
    data_in_rsc_WDATA("data_in_rsc_WDATA"), 
    data_in_rsc_AWREADY("data_in_rsc_AWREADY"), 
    data_in_rsc_AWVALID("data_in_rsc_AWVALID"), 
    data_in_rsc_AWUSER("data_in_rsc_AWUSER"), 
    data_in_rsc_AWREGION("data_in_rsc_AWREGION"), 
    data_in_rsc_AWQOS("data_in_rsc_AWQOS"), 
    data_in_rsc_AWPROT("data_in_rsc_AWPROT"), 
    data_in_rsc_AWCACHE("data_in_rsc_AWCACHE"), 
    data_in_rsc_AWLOCK("data_in_rsc_AWLOCK"), 
    data_in_rsc_AWBURST("data_in_rsc_AWBURST"), 
    data_in_rsc_AWSIZE("data_in_rsc_AWSIZE"), 
    data_in_rsc_AWLEN("data_in_rsc_AWLEN"), 
    data_in_rsc_AWADDR("data_in_rsc_AWADDR"), 
    data_in_rsc_AWID("data_in_rsc_AWID"), 
    data_in_rsc_req_vz("data_in_rsc_req_vz"), 
    data_in_rsc_rls_lz("data_in_rsc_rls_lz"), 
    hist_out_rsc_s_tdone("hist_out_rsc_s_tdone"), 
    hist_out_rsc_tr_write_done("hist_out_rsc_tr_write_done"), 
    hist_out_rsc_RREADY("hist_out_rsc_RREADY"), 
    hist_out_rsc_RVALID("hist_out_rsc_RVALID"), 
    hist_out_rsc_RUSER("hist_out_rsc_RUSER"), 
    hist_out_rsc_RLAST("hist_out_rsc_RLAST"), 
    hist_out_rsc_RRESP("hist_out_rsc_RRESP"), 
    hist_out_rsc_RDATA("hist_out_rsc_RDATA"), 
    hist_out_rsc_RID("hist_out_rsc_RID"), 
    hist_out_rsc_ARREADY("hist_out_rsc_ARREADY"), 
    hist_out_rsc_ARVALID("hist_out_rsc_ARVALID"), 
    hist_out_rsc_ARUSER("hist_out_rsc_ARUSER"), 
    hist_out_rsc_ARREGION("hist_out_rsc_ARREGION"), 
    hist_out_rsc_ARQOS("hist_out_rsc_ARQOS"), 
    hist_out_rsc_ARPROT("hist_out_rsc_ARPROT"), 
    hist_out_rsc_ARCACHE("hist_out_rsc_ARCACHE"), 
    hist_out_rsc_ARLOCK("hist_out_rsc_ARLOCK"), 
    hist_out_rsc_ARBURST("hist_out_rsc_ARBURST"), 
    hist_out_rsc_ARSIZE("hist_out_rsc_ARSIZE"), 
    hist_out_rsc_ARLEN("hist_out_rsc_ARLEN"), 
    hist_out_rsc_ARADDR("hist_out_rsc_ARADDR"), 
    hist_out_rsc_ARID("hist_out_rsc_ARID"), 
    hist_out_rsc_BREADY("hist_out_rsc_BREADY"), 
    hist_out_rsc_BVALID("hist_out_rsc_BVALID"), 
    hist_out_rsc_BUSER("hist_out_rsc_BUSER"), 
    hist_out_rsc_BRESP("hist_out_rsc_BRESP"), 
    hist_out_rsc_BID("hist_out_rsc_BID"), 
    hist_out_rsc_WREADY("hist_out_rsc_WREADY"), 
    hist_out_rsc_WVALID("hist_out_rsc_WVALID"), 
    hist_out_rsc_WUSER("hist_out_rsc_WUSER"), 
    hist_out_rsc_WLAST("hist_out_rsc_WLAST"), 
    hist_out_rsc_WSTRB("hist_out_rsc_WSTRB"), 
    hist_out_rsc_WDATA("hist_out_rsc_WDATA"), 
    hist_out_rsc_AWREADY("hist_out_rsc_AWREADY"), 
    hist_out_rsc_AWVALID("hist_out_rsc_AWVALID"), 
    hist_out_rsc_AWUSER("hist_out_rsc_AWUSER"), 
    hist_out_rsc_AWREGION("hist_out_rsc_AWREGION"), 
    hist_out_rsc_AWQOS("hist_out_rsc_AWQOS"), 
    hist_out_rsc_AWPROT("hist_out_rsc_AWPROT"), 
    hist_out_rsc_AWCACHE("hist_out_rsc_AWCACHE"), 
    hist_out_rsc_AWLOCK("hist_out_rsc_AWLOCK"), 
    hist_out_rsc_AWBURST("hist_out_rsc_AWBURST"), 
    hist_out_rsc_AWSIZE("hist_out_rsc_AWSIZE"), 
    hist_out_rsc_AWLEN("hist_out_rsc_AWLEN"), 
    hist_out_rsc_AWADDR("hist_out_rsc_AWADDR"), 
    hist_out_rsc_AWID("hist_out_rsc_AWID"), 
    hist_out_rsc_req_vz("hist_out_rsc_req_vz"), 
    hist_out_rsc_rls_lz("hist_out_rsc_rls_lz")
  {
    elaborate_foreign_module(hdl_name);
  }

  ~ccs_DUT_wrapper() {}
};
#endif

#endif

#ifdef CCS_SYSC
} // end namespace HDL
#endif
#endif


