directive set /SAD_MATCH/SAD_MATCH:core/core/loop_op:i(15:0).sva REGISTER_NAME loop_op:i(15:0).sva
directive set /SAD_MATCH/SAD_MATCH:core/core/loop_op:i(15:0).sva#1 REGISTER_NAME loop_op:i(15:0).sva
directive set /SAD_MATCH/SAD_MATCH:core/core/i(15:0).sva REGISTER_NAME i(15:0).sva
directive set /SAD_MATCH/SAD_MATCH:core/core/i(15:0).sva#1 REGISTER_NAME i(15:0).sva
directive set /SAD_MATCH/SAD_MATCH:core/core/k.sva(31:8) REGISTER_NAME k.sva(31:8)
directive set /SAD_MATCH/SAD_MATCH:core/core/o(7:0).sva REGISTER_NAME k.sva(31:8)
directive set /SAD_MATCH/SAD_MATCH:core/core/k.sva(7:6) REGISTER_NAME k.sva(7:6)
directive set /SAD_MATCH/SAD_MATCH:core/core/loop_1:loop_1:and.itm(7:6) REGISTER_NAME k.sva(7:6)
directive set /SAD_MATCH/SAD_MATCH:core/core/k.sva(3) REGISTER_NAME k.sva(3)
directive set /SAD_MATCH/SAD_MATCH:core/core/loop_1:loop_1:and.itm(3) REGISTER_NAME k.sva(3)
directive set /SAD_MATCH/SAD_MATCH:core/core/loop_8:slc(loop_8:acc)(5).itm REGISTER_NAME k.sva(3)
directive set /SAD_MATCH/SAD_MATCH:core/core/loop_lmm:i(15:0).sva REGISTER_NAME loop_lmm:i(15:0).sva
directive set /SAD_MATCH/SAD_MATCH:core/core/loop_lmm:i(15:0).sva#1 REGISTER_NAME loop_lmm:i(15:0).sva
directive set /SAD_MATCH/SAD_MATCH:core/core/loop_3:slc(loop_3:acc)(3).itm REGISTER_NAME loop_3:slc(loop_3:acc)(3).itm
directive set /SAD_MATCH/SAD_MATCH:core/core/loop_4:slc(loop_4:acc)(3).itm REGISTER_NAME loop_3:slc(loop_3:acc)(3).itm
directive set /SAD_MATCH/SAD_MATCH:core/core/loop_6:slc(loop_6:acc)(3).itm REGISTER_NAME loop_3:slc(loop_3:acc)(3).itm
directive set /SAD_MATCH/SAD_MATCH:core/core/loop_3:acc#12.sdt(3:0) REGISTER_NAME loop_3:acc#12.sdt(3:0)
directive set /SAD_MATCH/SAD_MATCH:core/core/loop_4:acc#5.itm REGISTER_NAME loop_3:acc#12.sdt(3:0)
directive set /SAD_MATCH/SAD_MATCH:core/core/loop_1:sad.lpi#4 REGISTER_NAME loop_1:sad.lpi#4
directive set /SAD_MATCH/SAD_MATCH:core/core/loop_1:sad.sva#1 REGISTER_NAME loop_1:sad.lpi#4
directive set /SAD_MATCH/SAD_MATCH:core/core/loop_1:z(3:0).sva REGISTER_NAME loop_1:z(3:0).sva
directive set /SAD_MATCH/SAD_MATCH:core/core/loop_1:z(3:0).sva#1 REGISTER_NAME loop_1:z(3:0).sva
directive set /SAD_MATCH/SAD_MATCH:core/core/n(3:0).sva REGISTER_NAME loop_1:z(3:0).sva
directive set /SAD_MATCH/SAD_MATCH:core/core/n(3:0).sva#1 REGISTER_NAME loop_1:z(3:0).sva
directive set /SAD_MATCH/SAD_MATCH:core/core/l(3:0).sva#1 REGISTER_NAME loop_1:z(3:0).sva
directive set /SAD_MATCH/SAD_MATCH:core/core/j(3:0).sva REGISTER_NAME j(3:0).sva
directive set /SAD_MATCH/SAD_MATCH:core/core/l(3:0).sva REGISTER_NAME j(3:0).sva
directive set /SAD_MATCH/SAD_MATCH:core/core/m(3:0).sva REGISTER_NAME j(3:0).sva
directive set /SAD_MATCH/SAD_MATCH:core/core/loop_1:y(3:0).sva REGISTER_NAME j(3:0).sva
directive set /SAD_MATCH/SAD_MATCH:core/core/loop_8:acc#10.itm REGISTER_NAME loop_8:acc#10.itm
directive set /SAD_MATCH/SAD_MATCH:core/core/k.sva(2:0) REGISTER_NAME loop_8:acc#10.itm
