
--------> ./rtl.vhdl 
-- ----------------------------------------------------------------------
--  HLS HDL:        VHDL Netlister
--  HLS Version:    10.4/828904 Production Release
--  HLS Date:       Thu Jul 25 13:12:11 PDT 2019
-- 
--  Generated by:   mdk@mdk-FX504
--  Generated date: Mon Oct 28 14:36:05 2019
-- ----------------------------------------------------------------------

-- 
-- ------------------------------------------------------------------
--  Design Unit:    histogram_main
-- ------------------------------------------------------------------

LIBRARY IEEE;

USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;


ENTITY histogram_main IS
  PORT(
    clk : IN STD_LOGIC;
    rst : IN STD_LOGIC
  );
END histogram_main;

ARCHITECTURE v2 OF histogram_main IS
  -- Default Constants

BEGIN
END v2;



