// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    10.4/828904 Production Release
//  HLS Date:       Thu Jul 25 13:12:11 PDT 2019
// 
//  Generated by:   mdk@mdk-FX504
//  Generated date: Mon Oct 28 14:36:06 2019
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    histogram_main
// ------------------------------------------------------------------


module histogram_main (
  clk, rst
);
  input clk;
  input rst;



  // Interconnect Declarations for Component Instantiations 
endmodule



