directive set /DCT/DCT:core/core/loop_lmm:i(22:0).sva#1 REGISTER_NAME loop_lmm:i(22:0).sva#1
directive set /DCT/DCT:core/core/loop_out:i(22:0).sva#1 REGISTER_NAME loop_lmm:i(22:0).sva#1
directive set /DCT/DCT:core/core/loop_lmm:i(22:0).sva(21:0) REGISTER_NAME loop_lmm:i(22:0).sva#1
directive set /DCT/DCT:core/core/loop_out:i(22:0).sva(21:0) REGISTER_NAME loop_lmm:i(22:0).sva#1
directive set /DCT/DCT:core/core/loop_12:mux#8.itm REGISTER_NAME loop_lmm:i(22:0).sva#1
directive set /DCT/DCT:core/core/loop_6:mux#8.itm REGISTER_NAME loop_lmm:i(22:0).sva#1
directive set /DCT/DCT:core/core/loop_3:k(3:1).sva(1:0) REGISTER_NAME loop_3:k(3:1).sva(1:0)
directive set /DCT/DCT:core/core/loop_9:k(3:1).sva(1:0) REGISTER_NAME loop_3:k(3:1).sva(1:0)
directive set /DCT/DCT:core/core/loop_10:m(0).sva REGISTER_NAME loop_10:m(0).sva
directive set /DCT/DCT:core/core/loop_4:l(0).sva REGISTER_NAME loop_10:m(0).sva
directive set /DCT/DCT:core/core/loop_11:x(3:0).sva(2:0) REGISTER_NAME loop_11:x(3:0).sva(2:0)
directive set /DCT/DCT:core/core/loop_5:x(3:0).sva(2:0) REGISTER_NAME loop_11:x(3:0).sva(2:0)
directive set /DCT/DCT:core/core/loop_13:z(3:0).sva(2:0) REGISTER_NAME loop_11:x(3:0).sva(2:0)
directive set /DCT/DCT:core/core/loop_7:z(3:0).sva(2:0) REGISTER_NAME loop_11:x(3:0).sva(2:0)
directive set /DCT/DCT:core/core/buf(7).lpi#10 REGISTER_NAME buf(7).lpi#10
directive set /DCT/DCT:core/core/buf(7).sva#4 REGISTER_NAME buf(7).lpi#10
directive set /DCT/DCT:core/core/buf(7).lpi#6 REGISTER_NAME buf(7).lpi#10
directive set /DCT/DCT:core/core/buf(7).sva#2 REGISTER_NAME buf(7).lpi#10
directive set /DCT/DCT:core/core/buf(7).sva#1 REGISTER_NAME buf(7).lpi#10
directive set /DCT/DCT:core/core/buf(7).sva#3 REGISTER_NAME buf(7).lpi#10
directive set /DCT/DCT:core/core/buf(0).lpi#10 REGISTER_NAME buf(0).lpi#10
directive set /DCT/DCT:core/core/buf(0).lpi#6 REGISTER_NAME buf(0).lpi#10
directive set /DCT/DCT:core/core/buf(0).sva#2 REGISTER_NAME buf(0).lpi#10
directive set /DCT/DCT:core/core/buf(0).sva#4 REGISTER_NAME buf(0).lpi#10
directive set /DCT/DCT:core/core/buf(0).sva#1 REGISTER_NAME buf(0).lpi#10
directive set /DCT/DCT:core/core/buf(0).sva#3 REGISTER_NAME buf(0).lpi#10
directive set /DCT/DCT:core/core/buf(6).lpi#10 REGISTER_NAME buf(6).lpi#10
directive set /DCT/DCT:core/core/buf(6).sva#4 REGISTER_NAME buf(6).lpi#10
directive set /DCT/DCT:core/core/buf(6).lpi#6 REGISTER_NAME buf(6).lpi#10
directive set /DCT/DCT:core/core/buf(6).sva#2 REGISTER_NAME buf(6).lpi#10
directive set /DCT/DCT:core/core/buf(6).sva#1 REGISTER_NAME buf(6).lpi#10
directive set /DCT/DCT:core/core/buf(6).sva#3 REGISTER_NAME buf(6).lpi#10
directive set /DCT/DCT:core/core/buf(1).lpi#10 REGISTER_NAME buf(1).lpi#10
directive set /DCT/DCT:core/core/buf(1).sva#4 REGISTER_NAME buf(1).lpi#10
directive set /DCT/DCT:core/core/buf(1).lpi#6 REGISTER_NAME buf(1).lpi#10
directive set /DCT/DCT:core/core/buf(1).sva#2 REGISTER_NAME buf(1).lpi#10
directive set /DCT/DCT:core/core/buf(1).sva#1 REGISTER_NAME buf(1).lpi#10
directive set /DCT/DCT:core/core/buf(1).sva#3 REGISTER_NAME buf(1).lpi#10
directive set /DCT/DCT:core/core/buf(5).lpi#10 REGISTER_NAME buf(5).lpi#10
directive set /DCT/DCT:core/core/buf(5).sva#4 REGISTER_NAME buf(5).lpi#10
directive set /DCT/DCT:core/core/buf(5).lpi#6 REGISTER_NAME buf(5).lpi#10
directive set /DCT/DCT:core/core/buf(5).sva#2 REGISTER_NAME buf(5).lpi#10
directive set /DCT/DCT:core/core/buf(5).sva#1 REGISTER_NAME buf(5).lpi#10
directive set /DCT/DCT:core/core/buf(5).sva#3 REGISTER_NAME buf(5).lpi#10
directive set /DCT/DCT:core/core/buf(2).lpi#10 REGISTER_NAME buf(2).lpi#10
directive set /DCT/DCT:core/core/buf(2).sva#4 REGISTER_NAME buf(2).lpi#10
directive set /DCT/DCT:core/core/buf(2).lpi#6 REGISTER_NAME buf(2).lpi#10
directive set /DCT/DCT:core/core/buf(2).sva#2 REGISTER_NAME buf(2).lpi#10
directive set /DCT/DCT:core/core/buf(2).sva#1 REGISTER_NAME buf(2).lpi#10
directive set /DCT/DCT:core/core/buf(2).sva#3 REGISTER_NAME buf(2).lpi#10
directive set /DCT/DCT:core/core/buf(4).lpi#10 REGISTER_NAME buf(4).lpi#10
directive set /DCT/DCT:core/core/buf(4).sva#4 REGISTER_NAME buf(4).lpi#10
directive set /DCT/DCT:core/core/buf(4).lpi#6 REGISTER_NAME buf(4).lpi#10
directive set /DCT/DCT:core/core/buf(4).sva#2 REGISTER_NAME buf(4).lpi#10
directive set /DCT/DCT:core/core/buf(4).sva#1 REGISTER_NAME buf(4).lpi#10
directive set /DCT/DCT:core/core/buf(4).sva#3 REGISTER_NAME buf(4).lpi#10
directive set /DCT/DCT:core/core/buf(3).lpi#10 REGISTER_NAME buf(3).lpi#10
directive set /DCT/DCT:core/core/buf(3).sva#4 REGISTER_NAME buf(3).lpi#10
directive set /DCT/DCT:core/core/buf(3).lpi#6 REGISTER_NAME buf(3).lpi#10
directive set /DCT/DCT:core/core/buf(3).sva#2 REGISTER_NAME buf(3).lpi#10
directive set /DCT/DCT:core/core/buf(3).sva#1 REGISTER_NAME buf(3).lpi#10
directive set /DCT/DCT:core/core/buf(3).sva#3 REGISTER_NAME buf(3).lpi#10
directive set /DCT/DCT:core/core/loop_11:and.stg_1_3.sva REGISTER_NAME loop_11:and.stg_1_3.sva
directive set /DCT/DCT:core/core/loop_5:and.stg_1_3.sva REGISTER_NAME loop_11:and.stg_1_3.sva
directive set /DCT/DCT:core/core/loop_11:and.stg_1_0.sva REGISTER_NAME loop_11:and.stg_1_0.sva
directive set /DCT/DCT:core/core/loop_5:and.stg_1_0.sva REGISTER_NAME loop_11:and.stg_1_0.sva
directive set /DCT/DCT:core/core/loop_11:and.stg_1_2.sva REGISTER_NAME loop_11:and.stg_1_2.sva
directive set /DCT/DCT:core/core/loop_5:and.stg_1_2.sva REGISTER_NAME loop_11:and.stg_1_2.sva
directive set /DCT/DCT:core/core/loop_11:and.stg_1_1.sva REGISTER_NAME loop_11:and.stg_1_1.sva
directive set /DCT/DCT:core/core/loop_5:and.stg_1_1.sva REGISTER_NAME loop_11:and.stg_1_1.sva
directive set /DCT/DCT:core/core/loop_12:y(3:0).sva(2:0) REGISTER_NAME loop_12:y(3:0).sva(2:0)
directive set /DCT/DCT:core/core/loop_6:y(3:0).sva(2:0) REGISTER_NAME loop_12:y(3:0).sva(2:0)
directive set /DCT/DCT:core/core/loop_12:y(3:0).sva#1 REGISTER_NAME loop_12:y(3:0).sva#1
directive set /DCT/DCT:core/core/loop_13:z(3:0).sva#1 REGISTER_NAME loop_12:y(3:0).sva#1
directive set /DCT/DCT:core/core/loop_6:y(3:0).sva#1 REGISTER_NAME loop_12:y(3:0).sva#1
directive set /DCT/DCT:core/core/loop_7:z(3:0).sva#1 REGISTER_NAME loop_12:y(3:0).sva#1
directive set /DCT/DCT:core/core/loop_12:mux#9.itm REGISTER_NAME loop_12:mux#9.itm
directive set /DCT/DCT:core/core/loop_6:mux#9.itm REGISTER_NAME loop_12:mux#9.itm
directive set /DCT/DCT:core/core/loop_12:asn#24.itm REGISTER_NAME loop_12:asn#24.itm
directive set /DCT/DCT:core/core/loop_6:asn#32.itm REGISTER_NAME loop_12:asn#24.itm
directive set /DCT/DCT:core/core/loop_12:slc(loop_12:acc#12)(3).itm REGISTER_NAME loop_12:slc(loop_12:acc#12)(3).itm
directive set /DCT/DCT:core/core/loop_6:slc(loop_6:acc#10)(3).itm REGISTER_NAME loop_12:slc(loop_12:acc#12)(3).itm
